development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7e6bd29b119a375599966a59035e3f35@spinyfin.redistogo.com:9036/
  channel_prefix: vonflix_production
